### ISSUE TITLE
Crash when cutting

### ISSUE THREAD

**Issue by kvnper** [nallath/ModelCutter#3] opened 2021-09-09 10:56 UTC
Crash when cutting object. Clicked Cut object at plane and crash occured.

**Important Note:** I'm using SmartAvionics latest cura build which may be causing this. Not a problem, if so.

![image](https://user-images.githubusercontent.com/47488385/132673630-29a230c5-4dba-40cd-8f81-a97d47db9b87.png)

Traceback (most recent call last):
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\Bindings\ActiveToolProxy.py", line 55, in triggerAction
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\ModelCutter\ModelCutter\ChopperTool.py", line 80, in cutObject
    half_one = trimesh.intersections.slice_mesh_plane(trimesh_mesh, plane_normal= plane_normal, plane_origin=[plane_position.x, plane_position.y, plane_position.z], cap=True)
  File "trimesh\intersections.py", line 642, in slice_mesh_plane
TypeError: slice_faces_plane() got an unexpected keyword argument 'cap'

Thread 0x00005c98 (most recent call first):
  File "threading.py", line 306 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 2184 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1496 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x0000327c (most recent call first):
  File "threading.py", line 306 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 2184 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1315 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000010dc (most recent call first):
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1221 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00004a60 (most recent call first):
  File "D:\Program Files\Ultimaker Cura (SA) v20210908\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 87 in _updateThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000050f4 (most recent call first):
  File "threading.py", line 306 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00003538 (most recent call first):
  File "threading.py", line 306 in wait
  File "threading.py", line 558 in wait
  File "D:\Program Files\Ultimaker Cura (SA) v20210908\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x0000083c (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00002794 (most recent call first):
  File "D:\Program Files\Ultimaker Cura (SA) v20210908\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00002d28 (most recent call first):
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Backend\Backend.py", line 165 in _storeStderrToLogThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005550 (most recent call first):
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Backend\Backend.py", line 153 in _storeOutputToLogThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00004df8 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000009a4 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005558 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000001cc (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000054fc (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005e30 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00001614 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00004b20 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00000ba0 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000058b4 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000051e8 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000054dc (most recent call first):
  File "serial\serialwin32.py", line 286 in read
  File "serial\serialutil.py", line 659 in read_until
  File "D:\Program Files\Ultimaker Cura (SA) v20210908\plugins\USBPrinting\AutoDetectBaudJob.py", line 76 in run
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 133 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Current thread 0x000038a4 (most recent call first):
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 396 in _logInfoWidget
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 182 in _createDialog
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 86 in __init__
  File "C:\Users\burto\cura\cura-build\build\inst\bin\cura_app.py", line 195 in exceptHook
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\Bindings\MainWindow.py", line 203 in mouseReleaseEvent
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 393 in exec_
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 869 in run
  File "C:\Users\burto\cura\cura-build\build\inst\bin\cura_app.py", line 269 in <module>
  File "Console.py", line 36 in run
  File "__startup__.py", line 74 in run

**Comment by nallath** [comment] 2021-09-09 13:36
Duplicate of #1

**Closed as completed by nallath** 2021-09-09 13:36 UTC
Labels: duplicate
